### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by lem21h** [asterisk/libpri#1]
Hi,

Recently I've started working with this library, but the software that I'm working on was build with use of libpri 1.4.11.5 and now I need to do the update.
By any chance is it possible to get somekind of documentation for this library?

**Comment by jcolp** [comment]
This is strictly a mirror of the libpri project. Any documentation would be included with the library or on wiki.asterisk.org, as libpri itself is an old project there isn't much except for the usage on the Asterisk side. I'd also suggest using the asterisk-dev mailing list[1] in the future for questions.

[1] http://lists.digium.com/mailman/listinfo/asterisk-dev
